feat: refactored into proper collection structure
kyetter/ansible-devspace-demo pull request #13
Opened 2023-05-02 04:47 UTC by jeffcpullen

This is a big one. I moved everything into a proper collection structure to prepare for ansible-test usage.

2023-05-02 04:53 UTC, jeffcpullen commented
So as not to lose the molecule tests that were there previously not in a folder, I moved them into the zipship.rhel.podman role.

2023-05-02 14:26 UTC, kyetter requested changes

2023-05-02 14:26 UTC, kyetter commented on zipship/rhel/roles/test_role/molecule/default/converge.yml
This test_role no longer works - I thought it was because it would need to be renamed to zipship.test_role to go with the restructuring but that didn't fix it and I also tried renaming the namespace in the meta/main.yml to point to zip ship and that also didn't work. I'm getting the below error: 


TASK [Include zipship.test_role] ***********************************************
ERROR! the role 'zipship.test_role' was not found in /projects/ansible-devspace-demo/zipship/rhel/roles/test_role/molecule/default/roles:/home/runner/.cache/ansible-compat/88d782/roles:/home/runner/.cache/molecule/test_role/default/roles:/projects/ansible-devspace-demo/zipship/rhel/roles:/home/runner/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/projects/ansible-devspace-demo/zipship/rhel/roles:/projects/ansible-devspace-demo/zipship/rhel/roles/test_role/molecule/default

The error appears to be in '/projects/ansible-devspace-demo/zipship/rhel/roles/test_role/molecule/default/converge.yml': line 9, column 15, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      ansible.builtin.include_role:
        name: "zipship.test_role"
              ^ here

PLAY RECAP *********************************************************************

2023-05-02 14:26 UTC, kyetter commented on zipship/rhel/roles/dev_env/molecule/default/converge.yml
>    gather_facts: true
Hey Jeff, I can't get a clean run here either 
Steps I ran:
-  molecule prepare
-  source ~/.bashrc
-  verified that oc worked in the terminal
-  molecule test

```
TASK [Create molecule instance as containers] **********************************
failed: [localhost] (item={'image': 'registry.redhat.io/rhel8/python-39', 'name': 'molecule-rhel8-python-39', 'workingDir': '/tmp'}) => {"ansible_loop_var": "item", "changed": false, "item": {"image": "registry.redhat.io/rhel8/python-39", "name": "molecule-rhel8-python-39", "workingDir": "/tmp"}, "msg": "Failed to import the required Python library (kubernetes) on workspacebcd999b20b70450d-5646cc7fb4-htzc4's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
failed: [localhost] (item={'image': 'registry.redhat.io/rhel8/python-38', 'name': 'molecule-rhel8-python-38', 'workingDir': '/tmp'}) => {"ansible_loop_var": "item", "changed": false, "item": {"image": "registry.redhat.io/rhel8/python-38", "name": "molecule-rhel8-python-38", "workingDir": "/tmp"}, "msg": "Failed to import the required Python library (kubernetes) on workspacebcd999b20b70450d-5646cc7fb4-htzc4's Python /usr/bin/python3. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```

2023-05-05 13:49 UTC, jeffcpullen commented
Decided this is the wrong way to do this. We should have a multi-project dev file to pull in content separately. We need to break the content and the environment into different repos.

2023-05-05 13:49 UTC, closed without merging